### ISSUE TITLE
PlatformIO Build Issue 

### ISSUE THREAD

**Issue by colelogan** [ardnew/ESP32-3248S035#2]
Updated PlatformIO and Python then Building this repo on my machine with platformIO on VSCode gives me this error: Might be something with path of esp32-3248s035 but it would be awesome if it was compatible out the gate. I'm not so good at code lingo so I dont know what to do to fix this issue. Fixing this issue would be awesome!

```Library Manager: Installing file://ESP32-3248S035=symlink://../../
Error: Traceback (most recent call last):
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__    
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\run\cli.py", line 145, in cli
    process_env(
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\run\cli.py", line 208, in process_env
    ).process()
      ^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\run\processor.py", line 81, in process
    install_project_env_dependencies(
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\package\commands\install.py", line 133, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\package\commands\install.py", line 252, in _install_project_env_libraries
    env_lm.install(
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 47, in install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 97, in _install
    pkg = self.install_from_uri(spec.uri, spec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 187, in install_from_uri
    shutil.copytree(_uri, tmp_dir, symlinks=True)
  File "C:\Users\colel\.platformio\python3\Lib\shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colel\.platformio\python3\Lib\shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('ESP32-3248S035=symlink://../../platformio\\.pio\\libdeps\\esp32-3248s035.lock', 'C:\\Users\\colel\\.platformio\\.cache\\tmp\\pkg-installing-u2dws9um\\platformio\\.pio\\libdeps\\esp32-3248s035.lock', '[Errno 13] Permission denied')]

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================```

**Comment by ardnew** [comment]
The last line of your output indicates there is a file permission issue:

```
shutil.Error: [('ESP32-3248S035=symlink://../../platformio\\.pio\\libdeps\\esp32-3248s035.lock', 'C:\\Users\\colel\\.platformio\\.cache\\tmp\\pkg-installing-u2dws9um\\platformio\\.pio\\libdeps\\esp32-3248s035.lock', '[Errno 13] Permission denied')]
```

But, your file paths imply you are on Windows, and I'm not sure if/how Python on Windows supports symlinks. 

You should be able to just replace the following line in the example's `platformio.ini`:

```ini
lib_deps =
	ESP32-3248S035=symlink://../../
```

with either of the following options:

```ini
lib_deps =
	ESP32-3248S035=file://C:/PATH/TO/WHERE/YOU/INSTALLED/ESP32-3248S035

; -- OR --

lib_deps =
	https://github.com/ardnew/ESP32-3248S035.git#main
```
